import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Agent Listing Guidelines',
  description: 'Guidelines for creating and publishing AI agent listings on AgentHub.',
};

export default function GuidelinesPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-2">Agent Listing Guidelines</h1>
        <p className="text-muted-foreground">Effective Date: April 2, 2026</p>
      </div>

      <div className="prose prose-lg dark:prose-invert max-w-none">
        <p>
          To maintain a trustworthy and high-quality marketplace, all Agent listings must comply
          with these Guidelines. Submissions that violate these rules may be rejected or removed.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Truthfulness & Accuracy</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Listings must truthfully represent the Agent&apos;s capabilities and limitations.</li>
          <li>Misleading claims, exaggerated performance metrics, or false promises are prohibited.</li>
          <li>If an Agent requires specific configuration, API keys, or dependencies, this must be clearly stated.</li>
          <li>Example: Avoid &quot;guaranteed 10x returns&quot; or &quot;100% automation&quot; unless fully documented and reproducible.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Security & Malicious Code</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Agents must NOT contain viruses, malware, spyware, or any code that harms users or systems.</li>
          <li>Agents must NOT attempt to bypass security controls, steal data, or impersonate legitimate services.</li>
          <li>If your Agent requires elevated permissions or accesses sensitive data, you must disclose this clearly and obtain user consent.</li>
          <li>We reserve the right to scan submissions for security risks and revoke listings that pose threats.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Intellectual Property</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You must own or have permission to use all code, models, content, and trademarks in your Agent listing.</li>
          <li>Do not submit Agents that infringe on copyrights, patents, or trademarks.</li>
          <li>Properly attribute third-party components, including open-source licenses.</li>
          <li>Include license information in your Agent&apos;s documentation if applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Content & Conduct</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Agents must not generate illegal content, hate speech, harassment, or explicit material.</li>
          <li>Agents must not facilitate phishing, fraud, or scams.</li>
          <li>Agents must not spam, bombard APIs, or engage in denial-of-service attacks.</li>
          <li>Agents must respect user privacy and not collect personal data without consent.</li>
          <li>Creators are responsible for content generated by their Agents, even if dynamic.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Pricing & Billing Transparency</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>If your Agent is not free, the pricing model (one-time, subscription, freemium) must be clearly indicated.</li>
          <li>All costs, currency, billing cycles, and cancellation policies must be disclosed before purchase.</li>
          <li>Do not use hidden fees or bait-and-switch pricing tactics.</li>
          <li>External payment links must direct to trusted providers (Stripe, PayPal, etc.).</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Compliance with Third-Party Services</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>If your Agent integrates with external services (OpenAI, Anthropic, Google, etc.), you must comply with their usage policies and Terms of Service.</li>
          <li>You must not circumvent rate limits, authentication, or IP bans for any service.</li>
          <li>Do not create Agents that impersonate official brands or services.</li>
          <li>Obtain proper API keys and respect usage quotas; disclose if the Agent requires an API key from the user.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Agent Quality & Performance</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Agents should be functional, reliable, and produce useful outputs.</li>
          <li>The Agent&apos;s purpose should be clear and valuable to potential users.</li>
          <li>Provide clear installation, configuration, and usage instructions.</li>
          <li>Include samples, screenshots, or a demo where possible.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Review Manipulation</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Pay-to-remove reviews, spam reviews, or purchase of positive reviews is prohibited.</li>
          <li>Do not incentivize users to leave reviews (e.g., &quot;review for a discount&quot;).</li>
          <li>Do not attack competitors with fake negative reviews.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Disclosure & Transparency</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>If your Agent uses AI models or datasets with known biases, disclose these limitations.</li>
          <li>If your Agent collects user data, describe what data is collected and how it is used in the <Link href="/legal/privacy" className="text-primary hover:underline">Privacy Policy</Link>.</li>
          <li>If your Agent is licensed (e.g., for medical, legal, financial purposes), include appropriate disclaimers.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Enforcement</h2>
        <p>
          We enforce these Guidelines through:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Pre-publication moderation</strong> — all new listings are reviewed before going live.</li>
          <li><strong>Post-publication audits</strong> — we may scan live listings for compliance.</li>
          <li><strong>User reports</strong> — users can flag listings that violate guidelines.</li>
          <li><strong>Actions:</strong> Warnings, listing removal, account suspension, or permanent ban depending on severity.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">11. Appeals</h2>
        <p>
          If your listing is rejected or removed, you may appeal by contacting us at{' '}
          <a href="mailto:appeals@agenthub.io" className="text-primary hover:underline">appeals@agenthub.io</a>.
          Include your listing URL/slug and the reason for reconsideration.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">12. Questions</h2>
        <p>
          Contact us at <a href="mailto:guidelines@agenthub.io" className="text-primary hover:underline">guidelines@agenthub.io</a>
          with questions about these Guidelines.
        </p>
      </div>

      <div className="mt-12 pt-6 border-t">
        <Link href="/" className="text-primary hover:underline">← Back to AgentHub</Link>
      </div>
    </div>
  );
}
