import { NextRequest, NextResponse } from 'next/server';
import { readFile, readdir } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

const SKILLS_DIR = join(process.cwd(), 'skill-packages');

/**
 * GET /api/skills/[slug]/install
 * Returns installation instructions and a curl-based install script for a skill package.
 *
 * Query params:
 *   format — "json" (default) returns structured data; "sh" returns a shell script
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;

  if (slug.includes('..') || slug.includes('/') || slug.includes('\\')) {
    return NextResponse.json({ error: 'Invalid slug' }, { status: 400 });
  }

  const skillDir = join(SKILLS_DIR, slug);
  if (!existsSync(skillDir)) {
    return NextResponse.json({ error: 'Skill package not found' }, { status: 404 });
  }

  const skillJsonPath = join(skillDir, 'skill.json');
  if (!existsSync(skillJsonPath)) {
    return NextResponse.json({ error: 'Invalid skill package' }, { status: 404 });
  }

  try {
    const raw = await readFile(skillJsonPath, 'utf-8');
    const manifest = JSON.parse(raw);

    const baseUrl = request.nextUrl.origin;
    const format = request.nextUrl.searchParams.get('format') || 'json';

    // Enumerate downloadable files
    const files = await listDownloadableFiles(skillDir, skillDir);

    const installInstructions = {
      skill: manifest.name,
      version: manifest.version,
      runtime: manifest.runtime || {},
      entrypoint: manifest.entrypoint || null,
      installSteps: [
        `1. Create skill directory: mkdir -p ~/.skills/${slug}`,
        `2. Download skill.json: curl -sO ${baseUrl}/api/skills/${slug}/download?file=skill.json`,
        `3. Download SKILL.md: curl -sO ${baseUrl}/api/skills/${slug}/download?file=SKILL.md`,
        ...(manifest.entrypoint
          ? [`4. Download entrypoint: curl -sO ${baseUrl}/api/skills/${slug}/download?file=${manifest.entrypoint}`]
          : []),
        `5. Move to skill directory: mv skill.json SKILL.md ~/.skills/${slug}/`,
        ...(manifest.runtime?.python
          ? [`6. Install Python deps if requirements.txt exists`]
          : []),
      ],
      files,
      curlInstallOneLiner: `mkdir -p ~/.skills/${slug} && cd ~/.skills/${slug} && curl -sO ${baseUrl}/api/skills/${slug}/download?file=skill.json && curl -sO ${baseUrl}/api/skills/${slug}/download?file=SKILL.md`,
    };

    if (format === 'sh') {
      const shellScript = `#!/bin/bash
# Install script for ${manifest.name} v${manifest.version}
# Generated by AgentHub Skill Package API

SKILL_DIR="$HOME/.skills/${slug}"
BASE_URL="${baseUrl}"

echo "📦 Installing ${manifest.name} v${manifest.version}..."
mkdir -p "$SKILL_DIR"
cd "$SKILL_DIR"

${files.map((f: string) => `curl -sLO "$BASE_URL/api/skills/${slug}/download?file=${f}"`).join('\n')}

echo "✅ ${manifest.name} installed to $SKILL_DIR"
echo "📖 Read $SKILL_DIR/SKILL.md for usage instructions"
`;

      return new NextResponse(shellScript, {
        status: 200,
        headers: {
          'Content-Type': 'text/x-shellscript',
          'Content-Disposition': `attachment; filename="install-${slug}.sh"`,
        },
      });
    }

    return NextResponse.json(installInstructions);
  } catch (err) {
    return NextResponse.json(
      { error: 'Failed to generate install instructions', details: String(err) },
      { status: 500 }
    );
  }
}

async function listDownloadableFiles(dir: string, base: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const fullPath = join(dir, entry.name);
    const relativePath = fullPath.replace(base + '/', '');

    if (entry.isDirectory()) {
      files.push(...(await listDownloadableFiles(fullPath, base)));
    } else {
      const ext = entry.name.includes('.') ? '.' + entry.name.split('.').pop()!.toLowerCase() : '';
      const allowed = new Set([
        '.md', '.json', '.js', '.ts', '.sh', '.py', '.yaml', '.yml', '.svg',
      ]);
      if (allowed.has(ext)) {
        files.push(relativePath);
      }
    }
  }

  return files;
}
